In [2]:
# ==========================================
# HEALTH IT DATASET — BASIC AUDIT
# ==========================================

health_it = pd.read_csv(
    "hospital-promoting-interoperability-chpl-linkage.csv"
)

print("Shape:", health_it.shape)

print("\nColumns:")
print(health_it.columns.tolist())

print("\nFirst 5 rows:")
display(health_it.head())

print("\nYears:")
print(
    health_it["year"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nUnique facilities:")
print(health_it["Facility.ID"].nunique())

print("\nUnique facility names:")
print(health_it["Facility.Name"].nunique())

Shape: (68446, 17)

Columns:
['Facility.ID', 'Facility.Name', 'Address', 'City.Town', 'State', 'ZIP.Code', 'County.Parish', 'Telephone.Number', 'Meets.criteria.for.promoting.interoperability.of.EHRs', 'Start.Date', 'End.Date', 'CEHRT.ID', 'chpl_id', 'product_database_id', 'developer_name', 'product_name', 'year']

First 5 rows:

,Facility.ID,Facility.Name,Address,City.Town,State,ZIP.Code,County.Parish,Telephone.Number,Meets.criteria.for.promoting.interoperability.of.EHRs,Start.Date,End.Date,CEHRT.ID,chpl_id,product_database_id,developer_name,product_name,year
0,10001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Y,01/01/2023,12/31/2023,0015CAN28DKT47C,15.04.04.1447.Epic.IN.23.1.220713,10942.0,Epic Systems Corporation,EpicCare Inpatient Base,2023
1,10001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Y,01/01/2023,12/31/2023,0015CAN28DKT47C,15.04.04.1447.Epic.IN.24.1.221222,11119.0,Epic Systems Corporation,EpicCare Inpatient Base,2023
2,10001,SOUTHEAST HEALTH MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,(334) 793-8701,Y,01/01/2023,12/31/2023,0015CAN28DKT47C,15.04.04.1447.Epic.IN.25.1.230315,11263.0,Epic Systems Corporation,EpicCare Inpatient Base,2023
3,10005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Y,01/01/2023,12/31/2023,0015C0HAX4ESQ0D,15.02.05.2966.INPR.01.01.0.220222,10837.0,"Inpriva, Inc.",hDirect Network Services,2023
4,10005,MARSHALL MEDICAL CENTERS,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,(256) 593-8310,Y,01/01/2023,12/31/2023,0015C0HAX4ESQ0D,15.04.04.3001.Care.03.03.1.230926,11348.0,Virtusa Corporation,CareDiscovery Electronic Quality Measures,2023

Years:
year
2023    33008
2024    35438
Name: count, dtype: int64

Unique facilities:
4654

Unique facility names:
4589

In [3]:
# ==========================================
# ROWS PER FACILITY
# ==========================================

rows_per_facility = (
    health_it
    .groupby("Facility.ID")
    .size()
)

print("Rows per facility:")
print(rows_per_facility.describe())

print("\nFacilities with more than 1 row:",
      (rows_per_facility > 1).sum())

print("\nFacilities with exactly 1 row:",
      (rows_per_facility == 1).sum())

Rows per facility:
count    4654.000000
mean       14.706919
std         9.611050
min         1.000000
25%         8.000000
50%        14.000000
75%        20.000000
max        81.000000
dtype: float64

Facilities with more than 1 row: 4588

Facilities with exactly 1 row: 66

In [4]:
# ==========================================
# WHY ARE THERE MULTIPLE ROWS PER FACILITY?
# ==========================================

# Select a facility that has many records
example_facility = (
    health_it["Facility.ID"]
    .value_counts()
    .idxmax()
)

print("Example Facility.ID:", example_facility)

example = health_it[
    health_it["Facility.ID"] == example_facility
].copy()

print("\nNumber of rows:", len(example))

display(example)

Example Facility.ID: 230046

Number of rows: 81

,Facility.ID,Facility.Name,Address,City.Town,State,ZIP.Code,County.Parish,Telephone.Number,Meets.criteria.for.promoting.interoperability.of.EHRs,Start.Date,End.Date,CEHRT.ID,chpl_id,product_database_id,developer_name,product_name,year
14736,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2023,12/31/2023,0015CR0QPL5MKZ4,15.04.04.1447.Beac.22.16.1.220318,10866.0,Epic Systems Corporation,Beacon Cancer Registry Reporting,2023
14737,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2023,12/31/2023,0015CR0QPL5MKZ4,15.04.04.1447.Beac.22.17.1.220511,10889.0,Epic Systems Corporation,Beacon Cancer Registry Reporting,2023
14738,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2023,12/31/2023,0015CR0QPL5MKZ4,15.04.04.1447.Beac.22.18.1.221202,11044.0,Epic Systems Corporation,Beacon Cancer Registry Reporting,2023
14739,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2023,12/31/2023,0015CR0QPL5MKZ4,15.04.04.1447.Beac.23.19.1.230308,11251.0,Epic Systems Corporation,Beacon Cancer Registry Reporting,2023
14740,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2023,12/31/2023,0015CR0QPL5MKZ4,15.04.04.1447.Beac.23.20.1.230530,11290.0,Epic Systems Corporation,Beacon Cancer Registry Reporting,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48855,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2024,12/31/2024,0015CMH4G69KFV8,15.04.04.1447.Nati.23.13.1.230530,11293.0,Epic Systems Corporation,National Healthcare Survey Reporting,2024
48856,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2024,12/31/2024,0015CMH4G69KFV8,15.04.04.1447.Nati.23.14.1.230830,11339.0,Epic Systems Corporation,National Healthcare Survey Reporting,2024
48857,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2024,12/31/2024,0015CMH4G69KFV8,15.04.04.1447.Synd.23.18.1.230308,11254.0,Epic Systems Corporation,Syndromic Surveillance Reporting,2024
48858,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2024,12/31/2024,0015CMH4G69KFV8,15.04.04.1447.Synd.23.19.1.230530,11292.0,Epic Systems Corporation,Syndromic Surveillance Reporting,2024
48859,230046,UNIVERSITY OF MICHIGAN HEALTH SYSTEM,"1500 E MEDICAL CENTER DRIVE, SPC 5474",ANN ARBOR,MI,48109,WASHTENAW,(734) 764-1505,Y,01/01/2024,12/31/2024,0015CMH4G69KFV8,15.04.04.1447.Synd.23.20.1.230905,11338.0,Epic Systems Corporation,Syndromic Surveillance Reporting,2024

In [5]:
for col in health_it.columns:
    print(
        f"{col}: "
        f"{example[col].nunique(dropna=False)} unique values"
    )

Facility.ID: 1 unique values
Facility.Name: 1 unique values
Address: 1 unique values
City.Town: 1 unique values
State: 1 unique values
ZIP.Code: 1 unique values
County.Parish: 1 unique values
Telephone.Number: 1 unique values
Meets.criteria.for.promoting.interoperability.of.EHRs: 1 unique values
Start.Date: 2 unique values
End.Date: 2 unique values
CEHRT.ID: 2 unique values
chpl_id: 65 unique values
product_database_id: 65 unique values
developer_name: 1 unique values
product_name: 8 unique values
year: 2 unique values

In [6]:
# ==========================================
# HEALTH IT: YEAR AND CRITERION AUDIT
# ==========================================

print("Year distribution:")
print(health_it["year"].value_counts(dropna=False).sort_index())

print("\nInteroperability criterion distribution:")
print(
    health_it[
        "Meets.criteria.for.promoting.interoperability.of.EHRs"
    ].value_counts(dropna=False)
)

print("\nUnique combinations of facility, year, and criterion:")
print(
    health_it[
        [
            "Facility.ID",
            "year",
            "Meets.criteria.for.promoting.interoperability.of.EHRs"
        ]
    ]
    .drop_duplicates()
    .shape
)

Year distribution:
year
2023    33008
2024    35438
Name: count, dtype: int64

Interoperability criterion distribution:
Meets.criteria.for.promoting.interoperability.of.EHRs
Y      65475
NaN     2971
Name: count, dtype: int64

Unique combinations of facility, year, and criterion:
(9220, 3)

In [8]:
# ==========================================
# STEP 2 — HEALTH IT IDENTIFIER AUDIT
# ==========================================

print("Health IT Facility.ID examples:")
print(
    health_it["Facility.ID"]
    .head(10)
    .tolist()
)

print("\nHealth IT Facility.ID data type:")
print(
    health_it["Facility.ID"].dtype
)

Health IT Facility.ID examples:
[10001, 10001, 10001, 10005, 10005, 10005, 10005, 10005, 10006, 10006]

Health IT Facility.ID data type:
int64

In [11]:
# ==========================================
# STEP 3 — HEALTH IT RECORD STRUCTURE
# ==========================================

# Number of unique facilities by year
facilities_by_year = (
    health_it
    .groupby("year")["Facility.ID"]
    .nunique()
)

print("Unique facilities by year:")
print(facilities_by_year)


# Unique CHPL records by year
print("\nUnique CHPL IDs by year:")
print(
    health_it
    .groupby("year")["chpl_id"]
    .nunique()
)


# Unique products by year
print("\nUnique products by year:")
print(
    health_it
    .groupby("year")["product_database_id"]
    .nunique()
)

Unique facilities by year:
year
2023    4593
2024    4627
Name: Facility.ID, dtype: int64

Unique CHPL IDs by year:
year
2023    306
2024    320
Name: chpl_id, dtype: int64

Unique products by year:
year
2023    304
2024    318
Name: product_database_id, dtype: int64

In [10]:
# ==========================================
# STEP 4 — CHECK FACILITY/YEAR DUPLICATION
# ==========================================

facility_year = (
    health_it[
        ["Facility.ID", "year"]
    ]
    .drop_duplicates()
)

print(
    "Unique facility-year combinations:",
    len(facility_year)
)

print("\nExample facilities with records in both years:")

year_counts = (
    facility_year
    .groupby("Facility.ID")["year"]
    .nunique()
)

print(
    year_counts.value_counts()
)

Unique facility-year combinations: 9220

Example facilities with records in both years:
year
2    4566
1      88
Name: count, dtype: int64